baseURL = "https://blog.bouni.de/"
languageCode = "en-us"
title = "Bouni's blog"
theme = "salix"
enableEmoji = true
publishDir = "/opt/docker/webserver/www/blog.bouni.de/"

[social]
  github = "https://github.com/bouni/"
  twitter = "https://twitter.com/bouni2016"


[params]
  Author = "Bouni"
  bio = "random bits and pieces"
  enableRSS = true
  avatarLink = "/"
  remark42SiteID = "blog"
  remark42Url = "https://comments.bouni.de"
  highlightWrap = false



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'onedark'
    tabWidth = 4


